server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cache_example
    username: postgres
    password: 1212
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true